// components/TimeInput.vue
<template>
  <div class="flex items-center">
    <label class="block text-left">
      <div class="px-2 text-1">Hours:</div>
      <input
        ref="hoursInput"
        :value="hours"
        type="number"
        pattern="-?\d+"
        name="hours"
        class="input text-lg font-mono"
        placeholder="00"
        @input="onInput">
    </label>
    <label class="block text-left">
      <div class="px-2 text-1">Minutes:</div>
      <input
        ref="minutesInput"
        :value="minutes"
        type="number"
        pattern="-?\d+"
        name="minutes"
        class="input text-lg font-mono"
        placeholder="00"
        @input="onInput">
    </label>
  </div>
</template>
<script>
export default {
  name: 'TimeInput',
  props: {
    value: {
      type: [String, Number],
      default: 0
    }
  },
  computed: {
    hours(){
      if (this.value >= 0)
        return Math.floor(Number(this.value)/60);
      else
        return Math.ceil(Number(this.value)/60);
    },
    minutes(){
      return (Number(this.value) % 60);
    }
  },
  methods: {
    onInput($event){
      let value = (Number(this.$refs.hoursInput.value) * 60  || -0) + (Number(this.$refs.minutesInput.value) || -0);
      this.$emit('update:value', value);
    }
  }
}
</script>

// src/components/TimeInput.tsx
import React, { useState, useEffect, useRef } from 'react';

interface TimeInputProps {
  value: number | string;
  onChange: (value: number | string) => void;
}

const TimeInput: React.FC<TimeInputProps> = ({ value = 0, onChange }) => {
  const hoursInputRef = useRef<HTMLInputElement>(null);
  const minutesInputRef = useRef<HTMLInputElement>(null);
  
  // Calculate hours and minutes from the value
  const getHours = (val: number | string): number => {
    const numVal = Number(val);
    return numVal >= 0 ? Math.floor(numVal / 60) : Math.ceil(numVal / 60);
  };
  
  const getMinutes = (val: number | string): number => {
    return Number(val) % 60;
  };
  
  const [hours, setHours] = useState<number>(getHours(value));
  const [minutes, setMinutes] = useState<number>(getMinutes(value));
  
  // Update local state when prop value changes
  useEffect(() => {
    setHours(getHours(value));
    setMinutes(getMinutes(value));
  }, [value]);
  
  const handleInput = () => {
    const hoursValue = Number(hoursInputRef.current?.value || 0);
    const minutesValue = Number(minutesInputRef.current?.value || 0);
    const totalValue = (hoursValue * 60 || 0) + (minutesValue || 0);
    
    onChange(totalValue);
  };
  
  return (
    <div className="flex items-center">
      <label className="block text-left">
        <div className="px-2 text-1">Hours:</div>
        <input
          ref={hoursInputRef}
          value={hours}
          type="number"
          pattern="-?\d+"
          name="hours"
          className="input text-lg font-mono"
          placeholder="00"
          onChange={handleInput}
        />
      </label>
      <label className="block text-left">
        <div className="px-2 text-1">Minutes:</div>
        <input
          ref={minutesInputRef}
          value={minutes}
          type="number"
          pattern="-?\d+"
          name="minutes"
          className="input text-lg font-mono"
          placeholder="00"
          onChange={handleInput}
        />
      </label>
    </div>
  );
};

export default TimeInput;
